jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: |
          node test.js
